TestDjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TestDjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),
)

posts/urls.py
from django.conf.urls import patterns, url

from posts import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^post/$', views.get_post, name='post'),
    url(r'^publisher/$', views.get_publisher, name='publisher'),
    url(r'^publisher/(?P<publisher_id>\d+)/$', views.profile, name='profile'),
    url(r'^(?P<post_id>\d+)/$', views.detail, name='detail'),
    url(r'^login$', views.connection, name='login'),
    url(r'^logout$', views.log_out, name='logout'),
    url(r'^post_delete_ajax$', views.deletePost, name='deletePost'),
    url(r'^vote_ajax$', views.vote, name='vote')
)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-theme.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">

    <script src="{% static "js/jquery-1.11.1.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

    {%  block head %}{% endblock %}
</head>
<body>

    <div class="container">
        <nav class="navbar navbar-default" role="navigation">
            <div class="container-fluid">
                {% if user.is_authenticated %}
                    <a href="{% url 'posts:logout' %}"><button type="button" class="btn btn-default navbar-btn">Sign out</button></a>
                    <p class="navbar-text navbar-right">Signed in as <a href="#" class="navbar-link">{{ user }}</a></p>
                {% else %}
                    <a href="{% url 'posts:login' %}"><button type="button" class="btn btn-default navbar-btn">Sign in</button></a>
                {% endif %}
            </div>
        </nav>


        {% block body %}{% endblock %}
    </div>

</body>
</html>