TestDjango/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'TestDjango.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^admin/', include(admin.site.urls)),
)

posts/urls.py
from django.conf.urls import patterns, url

from posts import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^post/$', views.get_post, name='post'),
    url(r'^publisher/$', views.get_publisher, name='publisher'),
    url(r'^publisher/(?P<publisher_id>\d+)/$', views.profile, name='profile'),
    url(r'^(?P<post_id>\d+)/$', views.detail, name='detail'),
    url(r'^login$', views.connection, name='login'),
    url(r'^logout$', views.log_out, name='logout'),
    url(r'^post_delete_ajax$', views.deletePost, name='deletePost'),
    url(r'^vote_ajax$', views.vote, name='vote')
)

posts/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils import timezone

class UserProfile(models.Model):
    user_auth = models.OneToOneField(User, primary_key=True)
    phone = models.CharField(max_length=20, verbose_name="Phone number", null=True, default=None, blank=True)
    date_born = models.DateField(verbose_name="Born Date", null=True, default=None, blank=True)
    last_connexion = models.DateTimeField(verbose_name="Date of last connexion", null=True, default=None, blank=True)

    def __str__(self):
        return self.user_auth.username

class Publisher(UserProfile):
    specialisation = models.CharField(max_length=50, verbose_name="Specialisation")


class Post(models.Model):
    publisher = models.ForeignKey(Publisher)
    name = models.CharField(max_length=200)
    link = models.URLField(max_length=200, null=True)
    date_pub = models.DateTimeField(auto_now_add=True)
    date_modif = models.DateTimeField(auto_now=True)
    votes = models.IntegerField(default=0)

    def was_published_recently(self):
        return self.date_pub >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'date_pub'
    was_published_recently.boolean = True
    was_published_recently.short_description = "Published recently?"

    def __str__(self):
        return self.name

class Comment(models.Model):
    user = models.ForeignKey(Publisher)
    post = models.ForeignKey(Post)
    content = models.TextField(max_length=200)
    date_pub = models.DateTimeField(auto_now_add=True)

class Vote(models.Model):
    post = models.ForeignKey(Post)
    user = models.ForeignKey(Publisher)
    date_vote = models.DateTimeField(auto_now_add=True)

posts/forms.py
from crispy_forms.bootstrap import FormActions
from django import forms
from django.contrib.auth import authenticate
from posts.models import Publisher
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder, Hidden


class PostForm(forms.Form):
    name = forms.CharField(
        label='Post',
        max_length=50,
        required=True
    )
    link = forms.URLField(
        label='Link',
        max_length=200,
        initial='http://',
        required=True
    )

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'name',
            'link',
            Submit('submit', 'Submit')
        )



class PublisherForm(forms.Form):
    firstname = forms.CharField(label = 'Firstname', max_length = 50, required = True)
    lastname = forms.CharField(label = 'Lastname', max_length = 50, required = True)
    login = forms.CharField(label = "Login")
    email = forms.EmailField(label = "Email")
    specialisation = forms.CharField(label = "Specialisation")
    password = forms.CharField(label = "Password", widget = forms.PasswordInput)
    password_bis = forms.CharField(label = "Password", widget = forms.PasswordInput)

    def clean(self):
        cleaned_data = super (PublisherForm, self).clean()
        password = self.cleaned_data.get('password')
        password_bis = self.cleaned_data.get('password_bis')
        if password and password_bis and password != password_bis:
            raise forms.ValidationError("Passwords are not identical.")
        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(PublisherForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'firstname',
            'lastname',
            'login',
            'email',
            'specialisation',
            'password',
            'password_bis',
            Submit('submit', 'Submit')
        )

class LoginForm(forms.Form):
    username = forms.CharField(label="Login")
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        if not authenticate(username=username, password=password):
            raise forms.ValidationError("Wrong login or password")
        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'username',
            'password',
            Submit('submit', 'Submit')
        )

class CommentForm(forms.Form):
    content = forms.CharField(label="Comment")

    def clean(self):
        cleaned_data = super(CommentForm, self).clean()
        content = self.cleaned_data.get('content')
        return self.cleaned_data

    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'POST'
        self.helper.layout = Layout(
            'content',
            Submit('submit', 'Submit')
        )

class DeletePostForm(forms.Form):
    post = forms.IntegerField()

class VoteForm(forms.Form):
    post = forms.IntegerField()
    vote = forms.IntegerField()

posts/views.py
import json

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http.response import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.core.urlresolvers import reverse


# Create your views here.
from django.views.decorators.csrf import csrf_exempt
from posts.forms import PostForm, PublisherForm, LoginForm, CommentForm, DeletePostForm, VoteForm
from posts.models import Post, Publisher, Comment


def index(request):
    all_posts = Post.objects.all().order_by('-votes')
    paginator = Paginator(all_posts, 5)
    page = request.GET.get('page')

    try:
        post_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        post_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g 9999), deliver last page of results.
        post_list = paginator.page(paginator.num_pages)

    return render(request, 'posts/index.html', {'post_list': post_list})

def detail(request, post_id):
    try:
        post = Post.objects.get(pk=post_id)
    except Post.DoesNotExist:
        raise Http404
    #return render(request, 'posts/detail.html', {'post': post})

    if request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            content = form.cleaned_data['content']

            c = Comment(content=content, post_id=post_id, user_id=request.user.id)
            c.save()

            return HttpResponseRedirect(reverse('posts:detail', args=[post_id]))
        else:
            render(request, 'posts/detail.html', {'post': post, 'form': form})
    else:
        form = CommentForm()
    form = CommentForm()
    return render(request, 'posts/detail.html', {'post': post, 'form': form})

#@login_required
def get_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            # process data in form.cleaned_data
            name = form.cleaned_data['name']
            link = form.cleaned_data['link']

            p = Post(name=name, link=link, publisher_id=request.user.id)
            p.save();

            #redirect
            return HttpResponseRedirect('/posts')

    else:
        form = PostForm()

    return render(request, 'posts/post.html', {'form': form})

#@login_required
def get_publisher(request):
    if request.POST:
        form = PublisherForm(request.POST)
        if form.is_valid():
            # process data in form.cleaned_data
            firstname = form.cleaned_data['firstname']
            lastname = form.cleaned_data['lastname']
            login = form.cleaned_data['login']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            specialisation = form.cleaned_data['specialisation']

            new_user = User.objects.create_user(username=login, email=email, password=password)
            new_user.isActive = True
            new_user.first_name = firstname
            new_user.last_name = lastname
            new_user.save()

            new_publisher = Publisher(user_auth=new_user, specialisation=specialisation)
            new_publisher.save()

            #redirect
            return HttpResponseRedirect(reverse('posts:index'))
        else:
            render(request, 'posts/publisher.html', {'form': form})

    else:
        form = PublisherForm()
    form = PublisherForm()
    return render(request, 'posts/publisher.html', {'form': form})


def connection(request):
    if request.POST:
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)

            if user:
                login(request, user)
                if request.GET.get('next') is not None:
                    return redirect(request.GET['next'])
                else:
                    return HttpResponseRedirect(reverse('posts:index'))

        return render(request, 'posts/connection.html', {'form': form})
    else:
        form = LoginForm()
    return render(request, 'posts/connection.html', {'form': form})

@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('posts:index'))

@login_required
def profile(request, publisher_id):
    return render(request, 'posts/profile.html')

@csrf_exempt
def deletePost(request):
    return_value = "0"
    if len(request.POST) > 0:
        form = DeletePostForm(request.POST)
        if form.is_valid():
            id_post = form.cleaned_data['post']
            post_record = Post.objects.get(id = id_post)
            post_record.delete()
            return_value = id_post
    return HttpResponse(json.dumps(return_value), content_type="application/json")

@csrf_exempt
def vote(request):
    return_value = "0"
    if len(request.POST) > 0:
        form = VoteForm(request.POST)
        if form.is_valid():
            id_post = form.cleaned_data['post']
            vote = form.cleaned_data['vote']
            post_record = Post.objects.get(id = id_post)
            post_record.votes += vote
            if post_record.votes < 0:
                post_record.votes = 0
            post_record.save()
            return_value = post_record.votes
    return HttpResponse(json.dumps(return_value), content_type="application/json")

posts/templates/posts/connection.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Connexion
{% endblock %}

{% block body %}

    {% if user.is_authenticated %}

        <h1>You are connected.</h1>
        <p>Your email: {{ user.email }}</p>

    {% else %}

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Login</h3>
            </div>
            <div class="panel-body">
                {% crispy form %}
            </div>
        </div>

    {% endif %}

{% endblock %}

posts/templates/posts/detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Post Detail
{% endblock %}

{% load static %}
{% block head %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% block body %}
    <h2>{{ post.name }}</h2>
    <h3> by {{ post.publisher }} on {{ post.date_pub|date }}</h3>

    <div>
        <div>Number of vote{{ post.votes|pluralize }} : <span id="post-vote">{{ post.votes }}</span></div>
        <button type="button" class="btn btn-default btn-xs" onclick="javascript:vote({{ post.id }}, 1, '{% url "posts:vote" %}');">
            <span class="glyphicon glyphicon-plus"></span> Vote Up
        </button>
        <button type="button" class="btn btn-default btn-xs" onclick="javascript:vote({{ post.id }}, -1, '{% url "posts:vote" %}');">
            <span class="glyphicon glyphicon-minus"></span> Vote Down
        </button>
    </div>

    {% if post.comment_set.count %}
    <h4>There {{ post.comment_set.count|pluralize:"is, are" }} {{  post.comment_set.count }} comment{{ post.comment_set.count|pluralize }} </h4>
    {% else %}
    <h4>There is no comment.</h4>
    {% endif %}

    <ul>
        {% for comment in post.comment_set.all %}

            <li>{{ comment.user }} : {{ comment.content }}</li>

        {% endfor %}
    </ul>

    {% if user.is_authenticated %}
        {% crispy form %}
    {% endif %}

{% endblock %}

posts/templates/posts/index.html
{% extends "base.html" %}

{% block title %}
    Posts
{% endblock %}

{% load static %}
{% block head %}
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}

{% block body %}

    {% if post_list %}

        <table class="table table-bordered table-striped table-condensed">
            <thead>
                <tr>
                    <td>Posts</td>
                    <td>Publisher</td>
                    <td>Publication date</td>
                    <td>Votes</td>
                    {% if user.is_authenticated %}<td>&nbsp;</td>{% endif %}
                </tr>
            </thead>
            <tbody>

                {% for post in post_list %}

                    <tr id="post_{{ post.id }}">
                        <td><a href="{% url 'posts:detail' post.id %}">{{ post.name }}</a></td>
                        {% if user.is_authenticated %}
                            <td><a href="{% url 'posts:profile' post.publisher_id %}">{{ post.publisher }}</a></td>
                        {% else %}
                            <td>{{ post.publisher }}</td>
                        {% endif %}
                        <td>{{ post.date_pub|date:'Y-m-d H:i:s' }}</td>
                        <td>{{ post.votes }}</td>
                        {% if user.is_authenticated %}
                            <td>
                                <button type="button" class="btn btn-default btn-xs" onclick="javascript:post_delete({{ post.id }}, '{% url "posts:deletePost" %}');">
                                    <span class="glyphicon glyphicon-remove"></span> Delete
                                </button>
                            </td>
                        {% endif %}
                    </tr>

                {% endfor %}

                <tr>
                    <td colspan="{% if user.is_authenticated %}5{% else %}4{% endif %}">

                        <div class="pagination">
                            <span class="step-links">
                                {% if post_list.has_previous %}
                                    <a href="?page={{ post_list.previous_page_number }}">previous</a>
                                {% endif %}

                                <span class="current">
                                    Page {{ post_list.number }} of {{ post_list.paginator.num_pages }}.
                                </span>

                                {% if post_list.has_next %}
                                    <a href="?page={{ post_list.next_page_number }}">next</a>
                                {% endif %}
                            </span>
                        </div>

                    </td>
                </tr>
            </tbody>
        </table>

    {% else %}

        <p>No posts found</p>

    {% endif %}

    {% if user.is_authenticated %}
        <a href="{% url 'posts:post' %}">
            <button type="button" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span> Add Post
            </button>
        </a>
    {% endif %}

{% endblock %}

posts/templates/posts/logout.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Logout
{% endblock %}

{% block body %}
    <h1>You are not connected.</h1>
{% endblock %}

posts/templates/posts/post.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    New Post
{% endblock %}

{% block body %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">New Post</h3>
        </div>

        {% if user.is_authenticated %}

        <div class="panel-body">
            {% crispy form %}
        </div>

        {% endif %}
    </div>

{% endblock %}

posts/templates/posts/publisher.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    New Publisher
{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">New Publisher</h3>
        </div>
        <div class="panel-body">
            {% crispy form %}
        </div>
    </div>

{% endblock %}